function sshscan
    echo "🌐 Enter subnet to scan (e.g. 192.168.1.0/24):"
    read subnet

    echo "🔐 Path to SSH key (or leave blank for default):"
    read key_path

    echo "🔎 Scanning $subnet for SSH..."

    if not type -q nmap
        echo "❌ nmap not installed. Install it first."
        return
    end

    set alive_hosts (nmap -p 22 --open --min-rate=500 -n $subnet | grep "^Nmap scan report" | awk '{print $NF}')

    if test (count $alive_hosts) -eq 0
        echo "😞 No SSH hosts found in $subnet."
        return
    end

    echo "✅ Found (count: (count $alive_hosts)) SSH-enabled hosts."

    echo "# Auto-generated by sshscan.fish" > ~/.ssh/config.sshscan

    for ip in $alive_hosts
        set last_octet (string split '.' $ip | tail -n1)

        if test "$ip" = "192.168.1.2"
            set host_alias "rpi"
            set user "pi"
        else
            set host_alias "srv-$last_octet"
            set user "wann"
        end

        echo "# Auto-added from sshscan" >> ~/.ssh/config.sshscan
        echo "Host $host_alias" >> ~/.ssh/config.sshscan
        echo "    HostName $ip" >> ~/.ssh/config.sshscan
        echo "    User $user" >> ~/.ssh/config.sshscan
        if test -n "$key_path"
            echo "    IdentityFile $key_path" >> ~/.ssh/config.sshscan
        end
        echo "" >> ~/.ssh/config.sshscan
    end

    echo "📁 Output saved to ~/.ssh/config.sshscan"

    echo "🔁 Do you want to append it to your main ~/.ssh/config? (y/n)"
    read answer
    if test "$answer" = "y"
        cat ~/.ssh/config.sshscan >> ~/.ssh/config
        echo "✅ Appended!"
    else
        echo "ℹ️ You can manually review it: less ~/.ssh/config.sshscan"
    end
end

